from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QMessageBox


class App(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi()
        self.retranslateUi()
        self.show()

    def setupUi(self):
        self.resize(603, 469)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.openDirBtn = QtWidgets.QPushButton(self.frame)
        self.openDirBtn.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.openDirBtn)
        self.jsonFileListWidget = QtWidgets.QListWidget(self.frame)
        self.jsonFileListWidget.setObjectName("listWidget_2")
        self.verticalLayout_2.addWidget(self.jsonFileListWidget)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.allLabelsComboBox = QtWidgets.QComboBox(self.frame)
        self.allLabelsComboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.allLabelsComboBox)
        self.labelAddBtn = QtWidgets.QPushButton(self.frame)
        self.labelAddBtn.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.labelAddBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.addLabelListWidget = QtWidgets.QListWidget(self.frame)
        self.addLabelListWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.addLabelListWidget)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.toModifyLineEdit = QtWidgets.QLineEdit(self.frame)
        self.toModifyLineEdit.setMinimumSize(QtCore.QSize(261, 31))
        self.toModifyLineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.toModifyLineEdit)
        self.modifyBtn = QtWidgets.QPushButton(self.frame)
        self.modifyBtn.setMinimumSize(QtCore.QSize(101, 41))
        self.modifyBtn.setObjectName("pushButton_4")
        self.horizontalLayout_4.addWidget(self.modifyBtn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.labelDelBtn = QtWidgets.QPushButton(self.frame)
        self.labelDelBtn.setMinimumSize(QtCore.QSize(101, 41))
        self.labelDelBtn.setObjectName("pushButton_3")
        self.verticalLayout_3.addWidget(self.labelDelBtn)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout.addWidget(self.frame)
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 603, 24))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "labelme-json-editer"))
        self.openDirBtn.setText(_translate("MainWindow", "Open Dir"))
        self.labelAddBtn.setText(_translate("MainWindow", "추가"))
        self.modifyBtn.setText(_translate("MainWindow", "수정하기"))
        self.labelDelBtn.setText(_translate("MainWindow", "삭제하기"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = App()
    sys.exit(app.exec_())
